version: '3'
services:
  app:
    container_name: minimalism-blog-keystone
    restart: always
    image: minimalism-blog-app
    ports:
      - 8082:8082
    environment:
      SERVER_PORT: 8082

  backend:
    container_name: minimalism-strapi
    restart: always
    image: docker.larsgerber.ch/blog/minimalism-backend:archive-strapi
    ports:
      - 8080:1337

# first visit https://github.com/larsgerber/minimalism-blog/blob/strapi/docker-compose.yml
# docker compose up
# username: lars.gerber@bluewin.ch
# password: Test-blog1
